# Generated by Django 4.2.2 on 2023-07-07 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Branch')),
                ('street', models.CharField(max_length=150, verbose_name='Street')),
                ('street_number', models.IntegerField(max_length=10, verbose_name='Street number')),
                ('neighborhood', models.CharField(max_length=50, verbose_name='Neighborhood')),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='what', to='booking.branch'),
        ),
    ]
