# Generated by Django 4.2.2 on 2023-07-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_branch_alter_booking_notes_booking_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='street_number',
            field=models.IntegerField(verbose_name='Street number'),
        ),
    ]
