# Generated by Django 4.2.2 on 2023-09-28 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_branch_street_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branch', to='booking.branch'),
        ),
    ]
