# Generated by Django 4.2.1 on 2023-06-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=50)),
                ('cellphone', models.IntegerField(max_length=11)),
                ('bathday', models.CharField(max_length=50)),
                ('comments', models.TextField()),
            ],
        ),
    ]
