# Generated by Django 4.2.1 on 2023-06-14 15:09

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-data'], 'verbose_name': 'Contact form', 'verbose_name_plural': 'Contact forms'},
        ),
        migrations.AddField(
            model_name='contact',
            name='read',
            field=models.BooleanField(blank=True, default=False, verbose_name='Read'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='bathday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='cellphone',
            field=models.IntegerField(validators=[base.models.validate_cellphone_length]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date sent'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=50, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
